name: vca_chat
description: VCA-Chat App.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  fluttertoast: ^8.2.2
  very_good_analysis: ^5.1.0
  easy_localization: ^3.0.3
  intl: ^0.18.0
  path: ^1.8.3
  json_annotation: ^4.8.1
  sqflite: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_logs: ^2.1.11
  logger: ^2.0.2+1
  auto_route: ^7.8.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  equatable: ^2.0.5

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/launcher-icon.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets section
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/launcher/
    - assets/translations/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
